# This action is centrally managed in https://github.com/designcontainer/.github/
# Don't make changes to this file outside of the .github repository!
# Files will get overwritten with changes made to the same file in the above mentioned repository.

name: Generate/update Composer file on schedule

on:
    workflow_dispatch:
    
jobs:
    replicate_changes:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2
            - name: Generate/update Composer file
              uses: designcontainer/workflow-composer-handler@master
              with:
                  github_token: ${{ secrets.BOT_TOKEN }}
                  approval_github_token: ${{ secrets.GITHUB_TOKEN }}
                  committer_username: designcontainer-bot
                  committer_email: tech@designcontainer.no
